#!/bin/sh

set -e

#DEB

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/connectors/cassandra'
DIR_CONF='/etc/sds/connectors/cassandra'
DIR_CONF='/etc/sds/connectors/cassandra'
DIR_LOG='/var/log/sds/connectors/cassandra'

mv /opt/sds/connectors/cassandra/bin/stratio-connector-cassandra* /opt/sds/connectors/cassandra/bin/stratio-connector-cassandra

chmod 755 /etc/init.d/connector_cassandra
chmod 755 /opt/sds/connectors/cassandra/bin
chmod +x /opt/sds/connectors/cassandra/bin/stratio-connector-cassandra
chmod +x /etc/default/cassandra_connector
export CASSANDRA_CONNECTOR_LIB=/opt/sds/connectors/cassandra
export CASSANDRA_CONNECTOR_CONF="/etc/sds/connectors/cassandra"


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi

  chown root:root /etc/init.d/connector_cassandra
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod -R 775 $DIR_INSTALL
  chmod 775 $DIR_LOG

  sed -i 's!"$BASEDIR"/conf!/etc/sds/connectors/cassandra!g' /opt/sds/connectors/cassandra/bin/stratio-connector-cassandra

  update-rc.d connector_cassandra defaults
  ;;

esac    


exit 0
