#!/bin/sh
### BEGIN INIT INFO
# Provides:          stratio-connector-cassandra
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       crossdata server script
### END INIT INFO
#export JAVA_HOME=/usr/java/default
#export JAVA=$JAVA_HOME/bin/java
RUNAS=root

PIDFILE=/var/run/sds/stratio-connector-cassandra.pid
LOGFILE=/var/log/sds/connectors/cassandra/stratio-connector-cassandra.log
start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  cd /opt/sds/connectors/cassandra/

  bin/stratio-connector-cassandra start
  echo 'Cassandra Connector started'
}

stop() {
# if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
#    echo 'Service not running' >&2
#    return 1
#  fi
#  echo 'Stopping service…' >&2
#  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
#  echo 'Service stopped' >&2
    cd /opt/sds/connectors/cassandra/
    bin/stratio-connector-cassandra stop
    echo 'Cassandra Connector stopped'
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f <NAME> remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 start|stop|restart|uninstall"
        exit 1

esac

exit 0

